[package]
name = "dot-dev"
version = "0.1.0"
authors = ["Thomas Gideon <cmdln@thecommandline.net>"]
edition = "2018"

[dependencies]
clap = "^2.32.0"
serde = "^1.0.80"
serde_json = "^1.0.33"
serde_derive = "^1.0.80"
failure = "~0.1.3"
crossterm = "~0.10.2"
log = "~0.4.8"
stderrlog = "~0.4.1"
